# Generated by Django 5.2.15 on 2026-06-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0001_initial'),
        ('notifications', '0002_remove_notification_notificatio_is_read_9edb86_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hearings.hearing'),
        ),
    ]
