# Generated by Django 5.2.15 on 2026-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_sent_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
