# Generated by Django 5.2.15 on 2026-07-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_sent_at_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_46ad24_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_f2898f_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_427e4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_schedul_21ac35_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_sent_902d06_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='last_sent_reminder',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
    ]
