# Generated by Django 5.2.15 on 2026-07-02 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0002_remove_hearing_reminder_sent_and_more'),
        ('notifications', '0008_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-scheduled_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('HEARING_CREATED', 'Hearing Created'), ('HEARING_REMINDER_DAY', 'Reminder Before One Day'), ('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('SYSTEM_MESSAGE', 'System Message')], db_index=True, default='HEARING_CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='hearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hearings.hearing'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='هل قرأ المستخدم الإشعار؟'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='هل تم إرسال إشعار سطح المكتب؟'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='وقت ظهور الإشعار', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('HEARING', 'Hearing'), ('PAYMENT', 'Payment'), ('SYSTEM', 'System')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notificatio_user_id_c291d5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at'], name='notificatio_schedul_21ac35_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_sent'], name='notificatio_user_id_8c763c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'scheduled_at'], name='notificatio_user_id_3efb32_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='notificatio_type_ea918f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event'], name='notificatio_event_0ebdc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('hearing__isnull', False)), fields=('hearing', 'event'), name='unique_hearing_notification'),
        ),
    ]
