# Generated by Django 5.2.15 on 2026-06-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateTimeField()),
                ('court_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('next_hearing_date', models.DateTimeField(blank=True, null=True)),
                ('judge_name', models.CharField(blank=True, max_length=150)),
                ('courtroom', models.CharField(blank=True, max_length=100)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
            ],
            options={
                'ordering': ['hearing_date'],
                'indexes': [models.Index(fields=['hearing_date'], name='hearings_he_hearing_493fc5_idx'), models.Index(fields=['status'], name='hearings_he_status_7ee3fd_idx')],
            },
        ),
    ]
