# Generated by Django 5.2.15 on 2026-07-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('hearings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='reminder_sent',
        ),
        migrations.AlterField(
            model_name='hearing',
            name='hearing_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['case'], name='hearings_he_case_id_6fbe1f_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['case', 'hearing_date'], name='hearings_he_case_id_9eeb46_idx'),
        ),
    ]
