# Generated by Django 5.2.15 on 2026-06-25 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('court_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('POSTPONED', 'Postponed'), ('WON', 'Won'), ('LOST', 'Lost'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('opponent_name', models.CharField(blank=True, max_length=255)),
                ('opponent_lawyer', models.CharField(blank=True, max_length=255)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='clients.client')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case_number'], name='cases_case_case_nu_a07304_idx'), models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'), models.Index(fields=['lawyer'], name='cases_case_lawyer__5023a5_idx'), models.Index(fields=['created_at'], name='cases_case_created_a9dee7_idx')],
            },
        ),
    ]
